apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tetrix
  template:
    metadata:
      labels:
        app: tetrix
    spec:
      containers:
      - name: tetrix
        image: cmilanf/tetrinetx
        ports:
        - containerPort: 31457
        - containerPort: 31458
        - containerPort: 80
        env:
        - name: OP_PASSWORD
          value: pass4word  
        - name: SPEC_PASSWORD
          value: pass4word
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        hostname: myhostname.com