apiVersion: v1
kind: Service
metadata:
  name: tetrix
spec:
  type: LoadBalancer
  ports:
  - name: port-31457
    port: 31457
    targetPort: 31457
  - name: port-31458
    port: 31458
    targetPort: 31458
  - name: port-80
    port: 80
    targetPort: 80
  selector:
    app: tetrix